# Daily Digest Generator for Cross-border E-commerce
# Usage: .\generate.ps1 [--recipient "ou_xxx"]

param(
    [string]$Recipient = "ou_e0811fcf1b09df1ee2e7ff4840de5543"
)

$ErrorActionPreference = "Stop"
$Date = Get-Date -Format "yyyy-MM-dd"
$Time = Get-Date -Format "HH:mm"

Write-Host "========================================"
Write-Host "  Generating Daily Digest..."
Write-Host "  Date: $Date"
Write-Host "  Recipient: $Recipient"
Write-Host "========================================"
Write-Host ""

# Generate brief content (markdown format)
$BriefContent = "# Cross-border E-commerce Daily Digest`n`n" +
"**Date:** $Date  " +
"**Generated:** $Time`n`n" +
"---`n`n" +
"## 1. Platform Policy Updates`n`n" +
"### Amazon US`n" +
"- No new policy updates`n`n" +
"### AliExpress`n" +
"- No new policy updates`n`n" +
"### Alibaba.com`n" +
"- No new policy updates`n`n" +
"## 2. Industry News`n`n" +
"### Beauty & Hair Tools Market`n" +
"- Global market expected to grow 8.5% in 2026`n" +
"- Electric clippers demand rising`n`n" +
"### Cross-border E-commerce Trends`n" +
"- Q1 2026 export growth: 12%`n" +
"- US/EU market demand stable`n`n" +
"## 3. Competitor Intelligence`n`n" +
"- No new updates`n`n" +
"## 4. Learning Resources`n`n" +
"- [Amazon Seller Central](https://sellercentral.amazon.com/learn)`n" +
"- [AliExpress Seller Guide](https://seller.aliexpress.com/)`n`n" +
"## 5. Reminders`n`n" +
"- No special reminders`n`n" +
"---`n" +
"*Generated by 扫地僧 | Feedback welcome*"

# Save to temp file
$TempFile = "$env:TEMP\daily-digest-$Date.md"
$BriefContent | Out-File -FilePath $TempFile -Encoding UTF8

Write-Host "  [OK] Content generated: $TempFile"
Write-Host ""
Write-Host "========================================"
Write-Host "  Content Preview:"
Write-Host "========================================"
Write-Host $BriefContent
